In [44]:
import pandas as pd
import ipaddress
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [45]:
data = pd.read_csv('dataset_sdn.csv')
data

,dt,switch,src,dst,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,...,pktrate,Pairflow,Protocol,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label
0,11425,1,10.0.0.1,10.0.0.8,45304,48294064,100,716000000,1.010000e+11,3,...,451,0,UDP,3,143928631,3917,0,0.0,0.0,0
1,11605,1,10.0.0.1,10.0.0.8,126395,134737070,280,734000000,2.810000e+11,2,...,451,0,UDP,4,3842,3520,0,0.0,0.0,0
2,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,1,3795,1242,0,0.0,0.0,0
3,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,2,3688,1492,0,0.0,0.0,0
4,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,3,3413,3665,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104340,5262,3,10.0.0.5,10.0.0.7,79,7742,81,842000000,8.184200e+10,5,...,0,0,ICMP,1,15209,12720,1,1.0,2.0,0
104341,5262,3,10.0.0.5,10.0.0.7,79,7742,81,842000000,8.184200e+10,5,...,0,0,ICMP,3,15099,14693,1,1.0,2.0,0
104342,5262,3,10.0.0.11,10.0.0.5,31,3038,31,805000000,3.180500e+10,5,...,1,0,ICMP,2,3409,3731,0,0.0,0.0,0
104343,5262,3,10.0.0.11,10.0.0.5,31,3038,31,805000000,3.180500e+10,5,...,1,0,ICMP,1,15209,12720,1,1.0,2.0,0
104344,5262,3,10.0.0.11,10.0.0.5,31,3038,31,805000000,3.180500e+10,5,...,1,0,ICMP,3,15099,14693,1,1.0,2.0,0

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104345 entries, 0 to 104344
Data columns (total 23 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt           104345 non-null  int64
 1   switch       104345 non-null  int64
 2   src          104345 non-null  object
 3   dst          104345 non-null  object
 4   pktcount     104345 non-null  int64
 5   bytecount    104345 non-null  int64
 6   dur          104345 non-null  int64
 7   dur_nsec     104345 non-null  int64
 8   tot_dur      104345 non-null  float64
 9   flows        104345 non-null  int64
 10  packetins    104345 non-null  int64
 11  pktperflow   104345 non-null  int64
 12  byteperflow  104345 non-null  int64
 13  pktrate      104345 non-null  int64
 14  Pairflow     104345 non-null  int64
 15  Protocol     104345 non-null  object
 16  port_no      104345 non-null  int64
 17  tx_bytes     104345 non-null  int64
 18  rx_bytes     104345 non-null  int64
 19  tx_kbps      104345 non-null  int64
 20  rx_kbps      103839 non-null  float64
 21  tot_kbps     103839 non-null  float64
 22  label        104345 non-null  int64
dtypes: float64(3), int64(17), object(3)
memory usage: 18.3+ MB

In [47]:
data.dtypes == 'object'

dt             False
switch         False
src             True
dst             True
pktcount       False
bytecount      False
dur            False
dur_nsec       False
tot_dur        False
flows          False
packetins      False
pktperflow     False
byteperflow    False
pktrate        False
Pairflow       False
Protocol        True
port_no        False
tx_bytes       False
rx_bytes       False
tx_kbps        False
rx_kbps        False
tot_kbps       False
label          False
dtype: bool

In [48]:
data['Protocol'].unique()

array(['UDP', 'TCP', 'ICMP'], dtype=object)

In [49]:
data['Protocol'] = data['Protocol'].map({'UDP' : 0, 'TCP' : 1, 'ICMP' : 2})

In [50]:
print(dict(data['Protocol'].value_counts()))

{2: np.int64(41321), 0: np.int64(33588), 1: np.int64(29436)}

In [51]:
data['src'] = data['src'].apply(lambda x: int(ipaddress.ip_address(x)))
data['dst'] = data['dst'].apply(lambda x: int(ipaddress.ip_address(x)))

In [52]:
data.dtypes == 'object'

dt             False
switch         False
src            False
dst            False
pktcount       False
bytecount      False
dur            False
dur_nsec       False
tot_dur        False
flows          False
packetins      False
pktperflow     False
byteperflow    False
pktrate        False
Pairflow       False
Protocol       False
port_no        False
tx_bytes       False
rx_bytes       False
tx_kbps        False
rx_kbps        False
tot_kbps       False
label          False
dtype: bool

In [53]:
data.dtypes == 'float64'

dt             False
switch         False
src            False
dst            False
pktcount       False
bytecount      False
dur            False
dur_nsec       False
tot_dur         True
flows          False
packetins      False
pktperflow     False
byteperflow    False
pktrate        False
Pairflow       False
Protocol       False
port_no        False
tx_bytes       False
rx_bytes       False
tx_kbps        False
rx_kbps         True
tot_kbps        True
label          False
dtype: bool

In [54]:
data.dtypes == 'int64'

dt              True
switch          True
src             True
dst             True
pktcount        True
bytecount       True
dur             True
dur_nsec        True
tot_dur        False
flows           True
packetins       True
pktperflow      True
byteperflow     True
pktrate         True
Pairflow        True
Protocol        True
port_no         True
tx_bytes        True
rx_bytes        True
tx_kbps         True
rx_kbps        False
tot_kbps       False
label           True
dtype: bool

In [55]:
data.isnull().sum()

dt               0
switch           0
src              0
dst              0
pktcount         0
bytecount        0
dur              0
dur_nsec         0
tot_dur          0
flows            0
packetins        0
pktperflow       0
byteperflow      0
pktrate          0
Pairflow         0
Protocol         0
port_no          0
tx_bytes         0
rx_bytes         0
tx_kbps          0
rx_kbps        506
tot_kbps       506
label            0
dtype: int64

In [56]:
data.shape

(104345, 23)

In [57]:
data.dropna()

,dt,switch,src,dst,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,...,pktrate,Pairflow,Protocol,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label
0,11425,1,167772161,167772168,45304,48294064,100,716000000,1.010000e+11,3,...,451,0,0,3,143928631,3917,0,0.0,0.0,0
1,11605,1,167772161,167772168,126395,134737070,280,734000000,2.810000e+11,2,...,451,0,0,4,3842,3520,0,0.0,0.0,0
2,11425,1,167772162,167772168,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,0,1,3795,1242,0,0.0,0.0,0
3,11425,1,167772162,167772168,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,0,2,3688,1492,0,0.0,0.0,0
4,11425,1,167772162,167772168,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,0,3,3413,3665,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104340,5262,3,167772165,167772167,79,7742,81,842000000,8.184200e+10,5,...,0,0,2,1,15209,12720,1,1.0,2.0,0
104341,5262,3,167772165,167772167,79,7742,81,842000000,8.184200e+10,5,...,0,0,2,3,15099,14693,1,1.0,2.0,0
104342,5262,3,167772171,167772165,31,3038,31,805000000,3.180500e+10,5,...,1,0,2,2,3409,3731,0,0.0,0.0,0
104343,5262,3,167772171,167772165,31,3038,31,805000000,3.180500e+10,5,...,1,0,2,1,15209,12720,1,1.0,2.0,0
104344,5262,3,167772171,167772165,31,3038,31,805000000,3.180500e+10,5,...,1,0,2,3,15099,14693,1,1.0,2.0,0

In [58]:
x = data.drop('label',axis = 1)
y = data['label']

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.30, random_state = 42)

In [59]:
dt = DecisionTreeClassifier()
dt.fit(xTrain, yTrain)
dtPred = dt.predict(xTest)

In [60]:
print(classification_report(yTest,dtPred))
print(confusion_matrix(yTest,dtPred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19112
           1       1.00      1.00      1.00     12192

    accuracy                           1.00     31304
   macro avg       1.00      1.00      1.00     31304
weighted avg       1.00      1.00      1.00     31304

[[19108     4]
 [    1 12191]]